all:
	g++ main.cpp -o main -IC:\Users\m235370\Desktop\Software_Engineering\crop-pocalypse\src\include -LC:\Users\m235370\Desktop\Software_Engineering\crop-pocalypse\src\lib -lmingw32 -lSDL2main -lSDL2